language: cpp
cache: apt

env:
  - SCCC_CONFIG=VCAN_FX15DEV
  - SCCC_CONFIG=HANDTECH_D10DEV
  - SCCC_CONFIG=2017_INNO
  - SCCC_CONFIG=2018_CREATIVE
  - SCCC_CONFIG=2018_CAMERA

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update
  - sudo apt-get install gcc-arm-none-eabi --allow-unauthenticated

script: make all
